### ISSUE TITLE
Failed when editing physics

### ISSUE THREAD

**Issue by badver** [UnderwaterApps/overlap2d-runtime-libgdx#19]
I tried to follow this tutorial http://overlap2d.com/making-physics-based-side-scroller-project-setup-part-1/ and when I edit physics for a ball, editor freezes.

java.lang.NullPointerException
	at com.uwsoft.editor.b.d.a.b.b(ItemPhysicsEditor.java:137)
	at com.uwsoft.editor.b.d.b.as.clicked(ItemPhysicsDialog.java:269)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTInput.processEvents(LwjglAWTInput.java:356)
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.render(LwjglAWTCanvas.java:257)
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas$1.paintGL(LwjglAWTCanvas.java:95)
	at org.lwjgl.opengl.AWTGLCanvas.paint(AWTGLCanvas.java:339)
	at org.lwjgl.opengl.AWTGLCanvas.update(AWTGLCanvas.java:368)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.awt.X11.XRepaintArea.updateComponent(XRepaintArea.java:60)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
	at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:591)
	at java.awt.Component.dispatchEventImpl(Component.java:4948)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:713)
	at java.awt.EventQueue$4.run(EventQueue.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by azakhary** [comment]
Physics freezes sometime happen, depending on exact actions, thanks for bringing this up, I will try to figure this one out.

P.S.
Please report editor related bugs in forums, this github project is for runtime only, and does not contain sources of the editor.

**Comment by azakhary** [comment]
you can now report o2d editor related bugs here: https://github.com/UnderwaterApps/overlap2d/issues
